### ISSUE TITLE
panel in topbar disabled

### ISSUE THREAD

**Issue by freddyw** [Vityacv/window-list-mod#3]
Love this extension but it disables the panel in the topbar. It greys out and I cannot click any of the icons on the panel. The window list in the top bar does work but without the panel the system is effectively useless. Looking glass shows no errors, nothing to be found in the journal as well. Trying to get this extension to work on Fedora 29/Gnome 3.30 (daily updates). On as side note, the previous version works fine on Fedora 28/Gnome 3.28 at the moment.

I freshly installed the window-list extension, copied it to a new folder, patched following the instructions, copied the metadata.json and glib schema (compiled the schema).

Any ideas what to test or try?

**Comment by Vityacv** [comment]
Somehow fedora package gnome-shell-extension is different from master? It says no global.screen exist
So if you use fedora source of window-list from fedora package and patch it - it works.
Here is attached file of extension that working with fedora 29.
[window-list-mod@vagonpop.gmail.com.zip](https://github.com/Vityacv/window-list-mod/files/2521757/window-list-mod.vagonpop.gmail.com.zip)

**Comment by freddyw** [comment]
Thanks for the help but it still does not (really) work however. With the fedora supplied gnome-shell-extension-window-list and your zip file, the same happens as my previous attempts. The window-list-mod works, but the top panel looks disabled somehow. When taking a closer look, I noticed a tiny blue line at the bottom of the panel. It it sort of hard to click the exact position though. Enlarging the panel heigth for Window List Mod really disables the top panel. So as long as I keep the panel heigth for Window List Mod below the top bar heigth is it sort of workable (though extensions like system-monitor are not really of much use). The older 'version 9' seems to be using a different approach altogether?

**Comment by sebastiendamaye** [comment]
Hi,
I confirm the exact same issue on my Fedora 29, fresh install. When I first installed the extension, it worked fine but after a 1st reboot, the window list extension seemed to completely overlap the top bar, hence making other icons under kind of a large bar that takes the full width and where there is no way to click on the other icons anymore (clock, network, ...). Too bad because this extension is so useful that it should be shipped in gnome by default!

**Comment by Vityacv** [comment]
Thanks for reports, but i can't reproduce issues
![fedora29](https://user-images.githubusercontent.com/20649019/47841085-77085580-ddc9-11e8-9549-505be6d2b937.png)
Also gnome-shell-extensions is not required.

**Comment by freddyw** [comment]
Not quite sure what really did the trick, but here is what I did. I usually use an X11 session, but switched to Wayland. Removed the gnome-shell-extension-window-list and disabled all extensions. Rebooted into a Wayland session and enabled the extensions I wanted. Then it seemed to be working. Logged into a X11 session and all seems to work now. I suspect an incompatibility with some other extension? If I ever find out which one I will be sure to let you know.

**Comment by freddyw** [comment]
Just ran in to the same thing when upgrading my main system. Disabling/Enabling the 'No Title Bar' ( by franglais125)  extension seems to do the trick!

**Comment by freddyw** [comment]
Looks like I was cheering a bit too early. It worked until I rebooted. Can't get it to work now, not even when disabling all other extensions. Too bad I already upgraded.

**Comment by freddyw** [comment]
Got it working now about fiddling with the some extensions (probably the Activities Configurator). Only after coming back from the screenlock, the extension fails again (restarting gnome-shell by 'Alt-F2 r' recovers it), logging this error in the journal:


gnome-shell[2030]: JS ERROR: Error: Expected type object for Argument 'actor' but got type 'undefined'
                   enablePanel@/home/freddy/.local/share/gnome-shell/extensions/window-list-mod@vagonpop.gmail.com/extension.js:800:4
                   WindowList/<@/home/freddy/.local/share/gnome-shell/extensions/window-list-mod@vagonpop.gmail.com/extension.js:862:19
                   addChrome@resource:///org/gnome/shell/ui/layout.js:800:9
                   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                   WindowList@/home/freddy/.local/share/gnome-shell/extensions/window-list-mod@vagonpop.gmail.com/extension.js:885:9
                   _buildWindowLists/<@/home/freddy/.local/share/gnome-shell/extensions/window-list-mod@vagonpop.gmail.com/extension.js:1337:40
                   _buildWindowLists@/home/freddy/.local/share/gnome-shell/extensions/window-list-mod@vagonpop.gmail.com/extension.js:1335:9
                   enable@/home/freddy/.local/share/gnome-shell/extensions/window-list-mod@vagonpop.gmail.com/extension.js:1326:9
                   enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:135:9
                   enableAllExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:342:13
                   enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:341:9
                   _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:369:9
                   _emit@resource:///org/gnome/gjs/modules/signals.js:128:27
                   _sync@resource:///org/gnome/shell/ui/sessionMode.js:206:9
                   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                   popMode@resource:///org/gnome/shell/ui/sessionMode.js:175:9
                   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                   _continueDeactivate@resource:///org/gnome/shell/ui/screenShield.js:1209:13
                   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                   deactivate/<@resource:///org/gnome/shell/ui/screenShield.js:1195:41
                   finish@resource:///org/gnome/shell/gdm/authPrompt.js:500:13
                   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                   finish@resource:///org/gnome/shell/ui/unlockDialog.js:147:9
                   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                   deactivate@resource:///org/gnome/shell/ui/screenShield.js:1195:13
                   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                   _init/</<@resource:///org/gnome/shell/ui/screenShield.js:539:54
                   _emit@resource:///org/gnome/gjs/modules/signals.js:128:27
                   _convertToNativeSignal@resource:///org/gnome/gjs/modules/overrides/Gio.js:117:5

**Comment by freddyw** [comment]
I seem to have found some sort of (stable) equilibrium. I suspect some sort of conflict with another extension, either Activities Configurator, No Title Bar or Extend Panel Menu. Playing around with disabling/enabling those gave me a working situation so far.
Closing this issue as no errors appear in the logs any more.
